// Snake by patrick
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.event.*;
import javax.swing.Timer;

public class Board extends javax.swing.JPanel {

    private Snake snake;
    private Food food;
    public static int numRows = 30;
    public static int numCols = 30;
    private ScoreBoard scoreBoard;

    private Timer timer;
    private int deltaTime;
    public static final int INITIAL_DELTA_TIME = 50;

    public static void setNumRows(int numRows) {
        Board.numRows = numRows;
    }

    public static void setNumCols(int numCols) {
        Board.numCols = numCols;
    }

    public int getSquareWidth() {
        return (int) (getWidth() / numCols);
    }

    public int getSquareHeight() {
        return (int) (getHeight() / numRows);
    }

    public Board() {
        initComponents();
        myInit();
    }

    public Board(int numRows, int numCols) {
        this.numRows = numRows;
        this.numCols = numCols;
    }

    private void myInit() {
        snake = new Snake(5, 5, 3);
        food = new Food(snake);
        deltaTime = INITIAL_DELTA_TIME;
        MyKeyAdapter keyAdapter = new MyKeyAdapter();
        addKeyListener(keyAdapter);
        //scoreBoard.setScore(0);
        
        createTime();
        setFocusable(true);

        timer.start();
    }

    private void createTime() {
        timer = new Timer(deltaTime, new ActionListener() {
        int specialCount = 0;
            @Override
            public void actionPerformed(ActionEvent ae) {
                if (!gameOver()) {
                    if(colideFood()){
                        if(specialCount == 10){
                            food.setIsSpecial(true);
                            food = new Food(snake);
                            snake.setRemainingNodes(5);
                            specialCount = 0;
                            //scoreBoard.incrementScore(5);
                        } else {
                            food.setIsSpecial(false);
                            food = new Food(snake);
                            snake.setRemainingNodes(1);
                            specialCount++;
                            //scoreBoard.incrementScore(1); 
                        }
                    }
                    snake.move();
                    repaint();

                } else {
                    timer.stop();
                }
                Toolkit.getDefaultToolkit().sync();
            }

        });
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        paintBoard((Graphics2D) g);
        snake.paint(g, getSquareWidth(), getSquareHeight());
        food.paint(g, getSquareWidth(), getSquareHeight());
        
    }

    public void paintBoard(Graphics2D g2d) {
        for (int row = 0; row < numRows; row++) {
            for (int col = 0; col < numCols; col++) {
                Util.drawSquare(g2d, row, col, getSquareWidth(), getSquareHeight(), new Color(255, 255, 255));

            }
        }
    }

   public boolean colideFood() {
        Node head = snake.getHeader();
            return food.getPosition().getCol() == head.getCol() && food.getPosition().getRow() == head.getRow();
    }

    public boolean gameOver() {
        if (!snake.canMove()) {
            return true;
        }
        return false;
    }


    class MyKeyAdapter extends KeyAdapter {

        @Override
        public void keyPressed(KeyEvent ev) {
            switch (ev.getKeyCode()) {
                case KeyEvent.VK_LEFT:
                    if (snake.getDirection() != Direction.RIGHT) {
                        snake.setDirection(Direction.LEFT);
                    }
                    break;
                case KeyEvent.VK_RIGHT:
                    if (snake.getDirection() != Direction.LEFT) {
                        snake.setDirection(Direction.RIGHT);
                    }
                    break;
                case KeyEvent.VK_UP:
                    if (snake.getDirection() != Direction.DOWN) {
                        snake.setDirection(Direction.UP);
                    }
                    break;
                case KeyEvent.VK_DOWN:
                    if (snake.getDirection() != Direction.UP) {
                        snake.setDirection(Direction.DOWN);
                    }
                    break;
                default:
                    break;
            }
            repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
