/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
// Snake by patrick
public class ScoreBoard extends javax.swing.JPanel {
    
    private int score;

    /**
     * Creates new form ScoreBoard
     */
    public ScoreBoard() {
        initComponents();
        incrementScore(0);
    }
    
    public void incrementScore(int increment) {
        score += increment;
        ScoreLabel.setText("Score: " + score);
    }

    public void setScore(int score) {
        this.score = score;
        incrementScore(0);
    }
    
    public int getScore() {
        return score;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScoreLabel = new javax.swing.JLabel();

        add(ScoreLabel);
        ScoreLabel.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ScoreLabel;
    // End of variables declaration//GEN-END:variables
}
